# Generated by Django 4.2 on 2023-04-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_service_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginemodel',
            name='type_dict',
            field=models.CharField(default='Модель двигателя', editable=False, max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='failuretype',
            name='type_dict',
            field=models.CharField(default='Характер отказа', editable=False, max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='frontaxle',
            name='type_dict',
            field=models.CharField(default='Передний управляемый мост', editable=False, max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='type_dict',
            field=models.CharField(default='Модель машины', editable=False, max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='maintaintype',
            name='type_dict',
            field=models.CharField(default='Вид ТО', editable=False, max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='rearaxlemodel',
            name='type_dict',
            field=models.CharField(default='Задний ведущий мост', editable=False, max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='recoverymethods',
            name='type_dict',
            field=models.CharField(default='Способ восстановления', editable=False, max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='transmissionmodel',
            name='type_dict',
            field=models.CharField(default='Трансмиссия', editable=False, max_length=32, verbose_name='Тип'),
        ),
    ]
