# Generated by Django 4.2 on 2023-04-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
        ('machine_service_app', '0002_alter_machine_client_alter_machine_service_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_app.customer', verbose_name='Клиент'),
        ),
    ]
