# Generated by Django 4.2 on 2023-04-09 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine_service_app', '0003_alter_machine_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='front_axle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frontaxle', to='machine_service_app.frontaxle', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='rear_axle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rearaxle', to='machine_service_app.rearaxlemodel', verbose_name='Модель ведущего моста'),
        ),
    ]
